### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by soxofaan** [utapyngo/pytest-unordered#7]
I'm considering to start using pytest-unordered in some projects, but the lack of documentation makes that an unfriendly move towards my coworkers.

A quickfix could be just providing some more examples in the README

**Comment by utapyngo** [comment]
Thank you @soxofaan, this is indeed a good idea.  I should have done this before but was hoping the project is simple enough to read the source code to understand how to use this 😂 .

Although I understand this is important, I am too busy at the moment. 
But if you create a pull request I will find some time to supplement and merge it. 
Thanks again for your contributions.
